build-composer-package:
    script:
        - sh -x /usr/local/sbin/buildComposerRepos $(composer info -s | awk '$1=="name"{print $3}')
    stage: build
    tags:
        - repo
    only:
        - master

rsync-repo:
    script:
        - sh -x /usr/local/sbin/rsyncGitRepo.sh myali
    stage: build
    tags:
        - dev
    only:
        - master
